version: 2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python3/load-cache
      - python3/install-deps
      - python3/save-cache
      - run:
          command: ./manage.py test
          name: Test
workflows:
  main:
    jobs:
      - build-and-test 
