# Generated by Django 4.0.1 on 2022-01-26 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_customer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 22, 48, 24, 656780, tzinfo=utc)),
        ),
    ]
